### ISSUE TITLE
add handling of 'maxRacking' in autoknit.js ?

### ISSUE THREAD

**Issue by gabrielle-ohlson** [textiles-lab/autoknit#12]
I noticed that there is an unhandled [`maxRacking:`](https://gist.github.com/gabrielle-ohlson/02dcc35b7919c01bb99d68e35f2ac92e#file-bunny-js-L21) arg in [`xfer_cycle({opts:})`](https://github.com/textiles-lab/autoknit/blob/master/node_modules/autoknit.js#L269), which seems particularly helpful in situations where, otherwise, the racking for the out.k file goes as high as 8 (see [this example](https://gist.github.com/gabrielle-ohlson/02dcc35b7919c01bb99d68e35f2ac92e#file-bunny-k-L9483)).

Might be worth adding a function to handle that? (maybe spacing transfers out over multiple consecutive passes so that the transfers can happen more gradually, or gradually transferring with a smaller rack value and knitting through the stacked loops [in a somewhat bindoff-like fashion]). I guess the main concern there would be maintaining the integrity of the shaping so that complying with `maxRacking` doesn't alter the appearance of the object too much... but, especially since I've been thinking about how to create a kniterate-friendly adaptation of autoknit (and kniterate doesn't handle rack values > 2 well at all [honestly, even 2 can break the yarn]), it feels like a relevant feature.

**Comment by vid8687** [comment]
autoknit.js does not handle any transfer logic. The transfer planner in this codebase assumes racking limits of (-8,8) and can absolutely generate the max value (although this might be too drastic). It can be limited by changing the transfer planner's configuration here : https://github.com/textiles-lab/autoknit/blob/e6ad08bab5e0714dc5877638f4e517da9ce730e8/schedule.cpp#L2820

**Comment by gabrielle-ohlson** [comment]
hm gotcha @vid8687, but it seems like `constraints.max_racking` in [schedule.cpp](https://github.com/textiles-lab/autoknit/blob/e6ad08bab5e0714dc5877638f4e517da9ce730e8/schedule.cpp#L2820) is already set to 3... but, while out.js files contains `xfer_cycle({maxRacking:3}...)` (as in accordance with the value set in schedule.cpp), the out.k files still include racking values between -8 & 8.

It seems like the files are using half-gauge, so that could somewhat account for the larger values, but since `constraints.max_racking = 3`, it would make more sense for the racking values in out.k to be max +/-6 not 8... 

what exactly is [schedule.cpp](https://github.com/textiles-lab/autoknit/blob/e6ad08bab5e0714dc5877638f4e517da9ce730e8/schedule.cpp) doing to enforce the racking limits? from what I can tell, it seems like it is just writing this string ([line 2844](https://github.com/textiles-lab/autoknit/blob/e6ad08bab5e0714dc5877638f4e517da9ce730e8/schedule.cpp)) to the out.js file:
```c++
"h.xfer_cycle({minFree:" + std::to_string(constraints.min_free) + ", maxFree:" + std::to_string(constraints.max_free) + ", maxRacking:" + std::to_string(constraints.max_racking) + "},\n"
	"             [" + from_str + "],\n"
	"             [" + to_str + "],\n"
	"             [" + transfers_str + "]);";
```
which is then not handled in `autoknit.js`.
(I could absolutely be missing something, though)

**Comment by vid8687** [comment]
Ah, I should have been clearer -- with half-gauging the transfer planner _should_ generate transfers within a racking range of (-2n+1,2n+1) which means it should have been (-7,7). So there might be an actual problem here with the transfer planning being off by 1 on these limits! (Will open an issue about that)
The constraints get used here https://github.com/textileslab/autoknit/blob/e6ad08bab5e0714dc5877638f4e517da9ce730e8/schedule.cpp#L2834 
Autoknit.js is more of knitout generation helper, it should probably throw a warning if it is generating transfers outside the max racking range and an error if it is outside the machines actual range.

**Comment by ixchow** [comment]
I think the issue here is "half-guage" vs "full-guage" limits. So I suspect that the limits are being followed, but that the half-gauging process is making it seem like they are not. However, always good to validate these sorts of things.

**Comment by gabrielle-ohlson** [comment]
why do all (or maybe just most) of the output files use half-gauge? (i.e. is it just generally favorable for 3D knitting, or a default in autoknit, etc)

also, is half-gauge vs. full-gauge an argument that can be included in the command to generate the .st file?

**Comment by gabrielle-ohlson** [comment]
also, not sure how easy this would be to do, but maybe including `max-racking:` as a command-line argument for `./schedule.exe` would be helpful, so it doesn't need to be changed in the schedule.ccp file

**Comment by ixchow** [comment]
> why not full gauge?

The collapse-stretch-expand algorithm is written for a machine with sliders so (in theory) it could be used in full gauge.

In practice, the machine won't allow any carrier movement if any stitches are held on sliders, so CSE could only be used in full gauge with very careful carrier parking (rather than -- as it is used now -- at any point it is needed).
