### ISSUE TITLE
Transfer planner fails to be within max racking range

### ISSUE THREAD

**Issue by vid8687** [textiles-lab/autoknit#13]
Transfer planner seems to generates transfers that are not strictly within max racking limits. See:
_Originally posted by @gabrielle-ohlson in https://github.com/textiles-lab/autoknit/issues/12#issuecomment-808289371_

**Comment by gabrielle-ohlson** [comment]
I just now noticed that the `rack -8` (outside of the max racking limits) that I mentioned in #12 was coming from `h.stash` not `h.xfer_cycle`, which in the particular js file I was look at, is this:
https://gist.github.com/gabrielle-ohlson/02dcc35b7919c01bb99d68e35f2ac92e#file-bunny-js-L2746-L2747

notably, it comes right after the additional `h.end_tube`, associated with #11 / #7 (which you just seemed to resolve in the most recent commit), so maybe that has something to do with it.

**Comment by vid8687** [comment]
Fixed [commit](https://github.com/textiles-lab/autoknit/commit/aac3eb649b7011fa06a8a0bebbef6f204ec6850e) . Additional "shifting" done by scheduler was not tracking racking limits (i.e., not a bug in the transfer planner)
