### ISSUE TITLE
Warning: Uniform 'p2l' does not exist in program 

### ISSUE THREAD

**Issue by rahul-mitra13** [textiles-lab/autoknit#14]
Hello, I'm building on a Linux OS. I believe I have all my dependencies because jam builds all the targets. However, when I run. `./interface obj:misc-cactus.obj constraints:misc-cactus.cons`, I get the following warnings, 

WARNING: Uniform 'p2l' does not exist in program. 
WARNING: Uniform 'p2l' does not exist in program. 
WARNING: Uniform 'p2l' does not exist in program. 
WARNING: Uniform 'p2l' does not exist in program. 
Read 0 vertices and 0 triangles from 'misc-cactus-obj'.
ERROR: model is empty

I presume it doesn't read from the obj file because of the warnings. This occurs with any obj file I try. I looked at Interface.cpp and it seems that p2l has to do with position to light space. I should also note that I'm building on a virtual machine. 

Thank you for putting up the code, I would appreciate any help or input regarding the above error.

**Comment by ixchow** [comment]
The warnings have nothing to do with the obj loading, they are just from some sloppy coding around the shaders used for visualization.

It appears you may have a typo in either your issue report or command line -- the informational message `Read 0 vertices and 0 triangles from 'misc-cactus-obj'.` is printing the name of the file in the `''` (see [line 94 of load_obj.cpp](https://github.com/textiles-lab/autoknit/blob/0021de31fbf0478668b898673c63c736c23216cb/load_obj.cpp#L94) ).

A simple check would be to make sure you are giving the proper path to the file -- e.g., does something like `wc misc-cactus.obj` (word count the file) work properly but `./interface obj:misc-cactus.obj` not work?

**Comment by rahul-mitra13** [comment]
I see. 

Yes, from my end it was a command line issue. Thank you for the quick response.
