### ISSUE TITLE
Exporting knit instructions for knitting by hand

### ISSUE THREAD

**Issue by anthonymesa** [textiles-lab/autoknit#17]
I wasn't sure where or how to ask this and an issue doesn't seem the right place, so please point me in the right direction if this should be asked elsewhere, but I am looking for a software that exports instructions for knitting by hand. Is this possible with this software? If not, is it possible to adapt this software to do so if I were to fork this repo?

**Comment by vid8687** [comment]
This code base does not generate hand knitting instructions. It could technically be extended to turn the generated instructions into some sort of hand knitting instructions. Caveat — might not be the most hand-knitter friendly instructions (symmetries are not enforced, decreases and increases may not follow a nicely aligned pattern, etc..)

**Comment by anthonymesa** [comment]
Awesome, thank you!
