### ISSUE TITLE
FT Jam is no longer supported by Homebrew

### ISSUE THREAD

**Issue by fhaugen** [textiles-lab/autoknit#19]
I'm currently getting blocked when trying to build Autoknit by this line in the instructions:

`brew install ftjam sdl2 glm eigen libpng`

> frances@Fs-Macbook-Air-202409 autoknit % brew install ftjam sdl2 glm eigen libpng
> 
> Warning: No available formula with the name "ftjam".
> ==> Searching for similarly named formulae and casks...
> Error: No formulae or casks found for ftjam.
> 

When I go here:
https://formulae.brew.sh/formula/ftjam

It 404s.

Do you have a recommended workaround? Thanks!

**Comment by ixchow** [comment]
I believe this is a documentation bug!

ftjam was the build tool we used to use for this code; but it looks like we've already updated to build with a `Maekfile.js` (a self-contained build script written in javascript).

So you should be able to just not install `ftjam` and the rest of the steps should still work.

(I will leave this issue open until we have fixed the README.)

**Comment by ixchow** [comment]
Actually, can't find this in the documentation, so I'm going to go ahead and close this issue. Maybe a stale release package?
