### ISSUE TITLE
error compiling with jam

### ISSUE THREAD

**Issue by guaje007** [textiles-lab/autoknit#4]
Hi,
I am trying to compile autoknit in windows but getting a couple errors:

C:\autoknit>jam
...found 187 target(s)...
...updating 3 target(s)...
C++ dist\ak-trim_model.obj
ak-trim_model.cpp
ak-trim_model.cpp(1): fatal error C1083: Cannot open include file: 'ak-pipeline.hpp': No such file or directory

cl /nologo /c /Fodist\ak-trim_model.obj /nologo /c /EHsc /W3 /WX /MD /Ikit-libs-win/out/include /Ikit-libs-win/out/include/SDL2 /Ikit-libs-win/out/libpng /wd4146 /wd4297 /wd4267 /wd4244 /DGLM_ENABLE_EXPERIMENTAL /D_USE_MATH_DEFINES /DHAVE_M_PI /DWIN32_LEAN_AND_MEAN /DKIT_RAW_SDL_EVENTS   /I. /I. /Ikit  /Tpak-trim_model.cpp

...failed C++ dist\ak-trim_model.obj ...
C++ dist\Interface.obj   
Interface.cpp
Interface.cpp(1401): error C3493: 'Slices' cannot be implicitly captured because no default capture mode has been specified
Interface.cpp(1406): error C3493: 'Rings' cannot be implicitly captured because no default capture mode has been specified

cl /nologo /c /Fodist\Interface.obj /nologo /c /EHsc /W3 /WX /MD /Ikit-libs-win/out/include /Ikit-libs-win/out/include/SDL2 /Ikit-libs-win/out/libpng /wd4146 /wd4297 /wd4267 /wd4244 /DGLM_ENABLE_EXPERIMENTAL /D_USE_MATH_DEFINES /DHAVE_M_PI /DWIN32_LEAN_AND_MEAN /DKIT_RAW_SDL_EVENTS   /I. /I. /Ikit  /TpInterface.cpp

...failed C++ dist\Interface.obj ...
...skipped interface.exe for lack of ak-trim_model.obj...
...failed updating 2 target(s)...
...skipped 1 target(s)...

"this error I edited asking to initiate Pipeline.hpp instead ak-pipeline.pp as it was not included in the folder, not sure if that is correct though"

C:\autoknit>jam
...found 186 target(s)...
...updating 3 target(s)...
C++ dist\ak-trim_model.obj
ak-trim_model.cpp
C++ dist\Interface.obj
Interface.cpp
Interface.cpp(1401): error C3493: 'Slices' cannot be implicitly captured because no default capture mode has been specified
Interface.cpp(1406): error C3493: 'Rings' cannot be implicitly captured because no default capture mode has been specified

cl /nologo /c /Fodist\Interface.obj /nologo /c /EHsc /W3 /WX /MD /Ikit-libs-win/out/include /Ikit-libs-win/out/include/SDL2 /Ikit-libs-win/out/libpng /wd4146 /wd4297 /wd4267 /wd4244 /DGLM_ENABLE_EXPERIMENTAL /D_USE_MATH_DEFINES /DHAVE_M_PI /DWIN32_LEAN_AND_MEAN /DKIT_RAW_SDL_EVENTS   /I. /I. /Ikit  /TpInterface.cpp

...failed C++ dist\Interface.obj ...
...skipped interface.exe for lack of Interface.obj...
...failed updating 1 target(s)...
...skipped 1 target(s)...
...updated 1 target(s)...

Any hint what might be happening?
Many thanks

**Comment by ixchow** [comment]
The "ak-pipeline.hpp" include was from another branch that was hastily merged owing to a bugfix. This has been fixed.

**Comment by ixchow** [comment]
The Slices/Rings capture error is because of some disagreements between compiler authors on how capturing static variables should work. The current version is (a) certainly wrong and (b) seems to work. I've tweaked the default capture specifier to be more correct, in hopes this will work for you, but I'm not at a windows computer at the moment.

**Comment by guaje007** [comment]
many thanks for your prompt reply yesterday. It is now running and I was able to successfully create the knitout file with knitting instructions.  Congratulations for this amazing development!
