### ISSUE TITLE
exe file

### ISSUE THREAD

**Issue by mskwarka** [textiles-lab/autoknit#5]
Is it (or will be) available as normal software or exe file? I am connected with knitting industry not coding and so far I am not able to compile this code and run as an application.

**Comment by ixchow** [comment]
This is research code, with quirks and a learning curve. Maintaining a public exe file is likely to cause more disappointment than satisfaction.

That said, we're happy to demo things for knitting industry folks. Get in touch via e-mail (see textiles-lab.github.io for principle members and contact info).
