### ISSUE TITLE
Error following tutorial

### ISSUE THREAD

**Issue by tanderson9** [textiles-lab/autoknit#6]
Getting the following error when at step 1:
~/Documents/autoknit$ ./interface obj:misc-cactus.obj constraints:misc-cactus.cons
bash: ./interface: No such file or directory

even though interface.cpp is clearly in the location. So I try and build it and then get this issue:

a91gnzz@a91gnzz-VirtualBox:~/Documents/autoknit$ g++ Interface.cpp
In file included from Interface.cpp:1:0:
Interface.hpp:3:10: fatal error: kit/kit.hpp: No such file or directory
 #include <kit/kit.hpp>
          ^~~~~~~~~~~~~

I check and kit/kit.hpp is present

**Comment by ixchow** [comment]
Did you complete the sections in the "building" part of the readme? If so, you should have an "dist\interface.exe" executable which you can run.

**Comment by tanderson9** [comment]
I should note that I am running this in virtualbox Ubuntu, and there seems to be a lot of calls that are not pointing to the correct things. For example #include <kit/kit.hpp> doesnt work but #include "kit/kit.hpp" does. From that more errors come up with the SDL's not being called correctly and so on

**Comment by ixchow** [comment]
Hmm, it sounds a lot like you aren't building using jam and the provided Jamfile, as described in the "building" portion of the readme. If you are, could you please provide an example of the output of building with ```jam -dx -q``` ("display actions, quit on first error")?

**Comment by gmoa2017** [comment]
any update on this?  I'm having the same issue.

**Comment by ixchow** [comment]
As far as I can tell, the above issues stemmed from not following the steps in the "building" section of the readme and using `jam` along with the provided `Jamfile`.

Please provide an example of the output of building with `jam -dx -q` ("display actions, quit on first error")?

**Comment by gmoa2017** [comment]
Hi, the output is:

g++ -c -o dist/Interface.o -std=c++11 -g -Wall -Werror -Ikit-libs-linux/libpng/include -DGLM_ENABLE_EXPERIMENTAL -Ikit-libs-linux/glm/include `PATH=kit-libs-linux/SDL2/bin:$PATH sdl2-config --cflags` -DKIT_RAW_SDL_EVENTS -O  -I. -I. -Ikit Interface.cpp


g++ -c -o dist/init.o -std=c++11 -g -Wall -Werror -Ikit-libs-linux/libpng/include -DGLM_ENABLE_EXPERIMENTAL -Ikit-libs-linux/glm/include `PATH=kit-libs-linux/SDL2/bin:$PATH sdl2-config --cflags` -DKIT_RAW_SDL_EVENTS -O  -I. -I. -Ikit init.cpp


g++ -c -o objs/kit/kit-SDL2.o -std=c++11 -g -Wall -Werror -Ikit-libs-linux/libpng/include -DGLM_ENABLE_EXPERIMENTAL -Ikit-libs-linux/glm/include `PATH=kit-libs-linux/SDL2/bin:$PATH sdl2-config --cflags` -DKIT_RAW_SDL_EVENTS -O  -Ikit -I. -Ikit kit/kit-SDL2.cpp


g++ -c -o objs/kit/Button.o -std=c++11 -g -Wall -Werror -Ikit-libs-linux/libpng/include -DGLM_ENABLE_EXPERIMENTAL -Ikit-libs-linux/glm/include `PATH=kit-libs-linux/SDL2/bin:$PATH sdl2-config --cflags` -DKIT_RAW_SDL_EVENTS -O  -Ikit -I. -Ikit kit/Button.cpp


g++ -std=c++11 -g -Wall -Werror -o dist/interface  dist/ak-trace_graph.o dist/ak-peel_slice-euclidean.o dist/ak-trim_model.o dist/ak-embedded_path.o dist/ak-build_next_active_chains.o dist/ak-link_chains.o dist/ak-optimal_link.o dist/ak-extract_level_chains.o dist/ak-find_first_active_chains.o dist/ak-sample_chain.o dist/Interface.o dist/init.o dist/load_obj.o dist/ak-load_constraints.o dist/ak-embed_constraints.o dist/ak-interpolate_values.o objs/kit/kit.o objs/kit/kit-SDL2.o objs/kit/Button.o objs/kit/Load.o objs/kit/MeshBuffer.o objs/kit/BoneAnimation.o objs/kit/GLProgram.o objs/kit/path.o objs/kit/load_save_png.o objs/Stitch.o  -Lkit-libs-linux/libpng/lib -lpng -Lkit-libs-linux/zlib/lib -lz `PATH=kit-libs-linux/SDL2/bin:$PATH sdl2-config --static-libs` -lGL


chmod 755 dist/interface

**Comment by ixchow** [comment]
That looks like it is succeeding in building `dist/interface` for you. What errors are you seeing?

**Comment by gmoa2017** [comment]
similarly to OP, ./interface is met with the error "no such file or directory."  I tried building with " $ g++ Interface.cpp " instead, and I altered #include <kit/kit.hpp> to #include "kit/kit.hpp", which helped, but now my main issue is that the SDL's aren't showing up for me either.  I am also running it in remote-WSL Ubuntu, VS code, on a windows 10 computer.

**Comment by ixchow** [comment]
Ah, thank you for highlighting that. It hadn't jelled for me that this may be a bug in the README -- the software builds into the `dist` directory, so ("obviously" -- like all hard-to-spot technical writing bugs) you will need to `cd dist` before running interface (or run `dist/interface` from the autoknit directory).

**Comment by gmoa2017** [comment]
oh, and I also tried copying the SDL's from the folder that was made when I initially tried installing autoknit through windows (but I had trouble with jam working so I switched to linux)--with those SDL's from the windows version now in my workspace, this is the error I'm receiving for $ g++ Interface.cpp:

Interface.hpp:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
Interface.hpp:15:28: error: ‘SDL_Event’ has not been declared
   15 |  virtual void handle_event(SDL_Event const &) override;
      |                            ^~~~~~~~~
Interface.hpp:15:15: error: ‘virtual void Interface::handle_event(const int&)’ marked ‘override’, but does not override
   15 |  virtual void handle_event(SDL_Event const &) override;
      |               ^~~~~~~~~~~~

**Comment by gmoa2017** [comment]
thanks! I did `cd dist` and this is the output:

error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error creating SDL window: No available video device
Aborted (core dumped)

**Comment by ixchow** [comment]
Great! What this, likely, means is that you are running without accelerated OpenGL drivers on Linux and so the interface has no way of creating a window to render into.

**Comment by ixchow** [comment]
> running `g++ Interface.cpp`

To forestall any future comments of this sort, this isn't (quite) how one generally builds C or C++ programs -- yes, can use the `g++` compiler, but the compiler needs to know more (specified by command-line arguments) to compile even simple programs. The most basic compile line you might use with g++ is `g++ -o myproj myprog.cpp` (the `-o` tells `g++` what to name the output file); generally you'll specify at least a few more flags like `-Wall` (produce more warnings -- helps to catch bugs in the code), `-Werror` (treat all warnings as errors -- forces you to fix bugs in the code), `-O2` (optimize the code), various `-Ipath/to/something` flags (tells the compiler where to find include files), various `-Dsomething=whatever` flags (define macros that the code may check with, e.g., `#ifdef`), and `-std=c++11` (select the version of the C++ language being used). You can see all of these in the commands that `jam` is running. (Oh, also the `-c` flag says 'make an object file, not a final executable'.)

**Comment by gmoa2017** [comment]
hm... I have accelerated OpenGL drivers on my windows computer (I have intel (R) iris (R) plus graphics) but I'm not quite sure how to get OpenGL to work while I'm using ubuntu to access linux remotely.  If you have any ideas, let me know.  Otherwise, thanks so much for all of your help.

**Comment by ixchow** [comment]
I've added support to the repository for automatically building releases, so that folks such as yourself won't need to build to try out the code. See https://github.com/textiles-lab/autoknit/releases .
