### ISSUE TITLE
Fails to in yarn after out

### ISSUE THREAD

**Issue by ixchow** [textiles-lab/autoknit#7]
In branching structures, no knitout instruction is generated to bring the yarn in again after finishing one branch.

This seems to be a problem with ```autoknit.js```, which should remember which yarns are currently active and use a tuck pattern to bring in the ones that are not. Possibly this can be ported from the visual knit programming codebase.

**Comment by gabrielle-ohlson** [comment]
resurfacing this issue, since it persists. has there been any progress with addressing it in the visual knit programming codebase?

**Comment by vid8687** [comment]
Fixed by letting autoknit.js module keep track of yarns. (Does not do a tuck pattern -- calls inhook if yarn is used without it,  releasehook after a few(5) loops have been made or before a xfer instruction with pending release hooks)
